### ISSUE TITLE
splat.getSpectrum says retrieved files are corrupted

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#137]
sp0 = splat.getSpectrum(shortname='1540-5101')[0]

Retrieving 3 files

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-175-7f4b8c7d01ae> in <module>()
----> 1 sp0 = splat.getSpectrum(shortname='1540-5101')[0]
      2 sp1 = splat.getSpectrum(shortname='1540-5101')[1]
      3 sp2 = splat.getSpectrum(shortname='1540-5101')[2]

~/Python/splat/splat/core.py in getSpectrum(getList, limit, *args, **kwargs)
   3073 
   3074 def getStandard(spt, **kwargs):
-> 3075     '''
   3076     :Purpose: Gets one of the pre-defined spectral standards from the SPLAT library.
   3077 

~/Python/splat/splat/core.py in __init__(self, *args, **kwargs)
    444 # convert to numpy arrays
    445             self.wave = numpy.array(self.wave)
--> 446             self.flux = numpy.array(self.flux)
    447             self.noise = numpy.array(self.noise)
    448 # enforce positivity and non-nan

~/Python/splat/splat/core.py in readSpectrum(verbose, *args, **kwargs)
   3990                 d = numpy.genfromtxt(os.path.normpath(file), comments='#', unpack=False, \
   3991                     missing_values = ('NaN','nan'), filling_values = (numpy.nan)).transpose()
-> 3992             except ValueError:
   3993                 d = numpy.genfromtxt(os.path.normpath(file), comments=';', unpack=False, \
   3994                      missing_values = ('NaN','nan'), filling_values = (numpy.nan)).transpose()

/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in fitsopen(name, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
    162     if not name:
    163         raise ValueError('Empty filename: {!r}'.format(name))
--> 164 
    165     return HDUList.fromfile(name, mode, memmap, save_backup, cache,
    166                             lazy_load_hdus, **kwargs)

/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in fromfile(cls, fileobj, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
    398         """
    399 
--> 400         return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
    401                              save_backup=save_backup, cache=cache,
    402                              lazy_load_hdus=lazy_load_hdus, **kwargs)

/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in _readfrom(cls, fileobj, data, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
   1019             # Close the file if necessary (issue #6168)
   1020             if hdulist._file.close_on_error:
-> 1021                 hdulist._file.close()
   1022 
   1023             raise OSError('Empty or corrupt FITS file')

OSError: Empty or corrupt FITS file

**Comment by daniellabardalezgagliuffi** [comment]
FYI, only happens with unpublished files

**Comment by aburgasser** [comment]
Excellent clue - this is part of data re-org, and things should be fixed now. Be sure to delete corrupt files on your machine

**Comment by daniellabardalezgagliuffi** [comment]
I'm not sure how to identify "corrupted" files. The first file where this is choking (12979_12709.fits) is not corrupted when I open it on SAO viewer. I still have this problem despite having SPLAT version '2018.07.29'.
